import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PCBC Stat Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[url('../assets/baseball-field.jpg')] bg-no-repeat bg-cover h-screen`}>
        <div className="absolute inset-0 bg-black bg-cover bg-opacity-75">
          {children}
        </div>
      </body>
    </html>
  );
}
